name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binaries
      run: |
        make build-all VERSION=${{ steps.get_version.outputs.VERSION }}

    - name: Create release archives
      run: |
        make release-archives VERSION=${{ steps.get_version.outputs.VERSION }}

    - name: Generate checksums
      run: |
        cd build/releases
        sha256sum * > checksums.txt
        cat checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/releases/*
        body: |
          ## Changes
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ### Binary Downloads
          Download the appropriate binary for your platform from the assets below.
          
          ### Using Go Install
          ```bash
          go install github.com/siyuan-infoblox/go-imports-group@${{ steps.get_version.outputs.VERSION }}
          ```
          
          ### Checksums
          All binaries have been checksummed for verification.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
